name: pacs
holdout_fraction: 0.2
uda_holdout_fraction: 0
class_balanced: false
data_augmentation: true
target_envs:
  - 0
full_domains:
  - art
  - cartoons
  - photos
  - sketches
num_classes: 7
num_envs: 4
seed: 0
str: name=${.name}-target_envs=${.target_envs}-seed=${.seed}