name: vlcs
holdout_fraction: 0.2
uda_holdout_fraction: 0
class_balanced: false
data_augmentation: true
target_envs:
  - 0
full_domains:
  - Caltech101
  - LabelMe
  - SUN09
  - VOC2007
num_classes: 5
num_envs: 4
seed: 0
str: name=${.name}-target_envs=${.target_envs}-seed=${.seed}