defaults:
  - optimizer: adam
method: diwa

#* diwa training
base_method: ERM
init_method: -1
weight_average_method: uniform # uniform, restricted
diwa_path: ./libs/diwa
weight_path: ${.diwa_path}/train_output/${..dataset.name}/${.base_method}/${..dataset.target_envs}/${.init_method}/trial_seed=${..dataset.seed}/${.weight_average_method}.pt

batch_size: 32
max_steps: -1
max_epochs: 60
seed: 0
input_e: false
monitor: source_val_acc
is_domainbed: false

str: method=${.method}-seed=${.seed}-init_method=${.init_method}-weight_average_method=${.weight_average_method}-base_method=${.base_method}-dataset=${..dataset.name}-target_envs=${..dataset.target_envs}-input_e=${.input_e}-monitor=${.monitor}-is_domainbed=${.is_domainbed}