defaults:
  - optimizer: adam
method: nuc
batch_size: 32
max_steps: -1
max_epochs: 60
seed: 0
input_e: false
monitor: source_val_loss #!fixme
is_domainbed: false
nuc_scale: 1e-2

str: method=${.method}-nuc_scale=${.nuc_scale}-batch_size=${.batch_size}-training_seed=${.seed}/optimizer=${.optimizer.str}